on: push
jobs:
	test:
		runs-on: macos-latest
		steps:
			- uses: actions/checkout@v2
			- name: Test
			  run: |
			   		/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift test
		